### PR TITLE
additions to characters.json

### PR DESCRIPTION
**Pull request by codemasher**
A couple of additions to characters.json as per this forum thread: https://forum-en.guildwars2.com/forum/community/api/Character-position/5254020

### CODE REVIEW

**Comment by lye** [comment]
That pile of data is, uhh, stored in different servers with different TTLs; roughly:

 * Online status (incl. which map and character is logged in) is in the "online status server" and is up-to-date within ~30 seconds.
 * Supply info is owned by the map instance server; the API's read-only snapshots are only updated every 5 minutes.

So for the WvW commander bit, it's totally infeasible. The rest of it is fine, but it needs to be put behind a new scope (e.g., "presence" or something) since I imagine there's quite a few people who don't want to grant access to that.

**Comment by codemasher** [comment]
Would it be possible to add the supply count to the mumble link data instead? This way we'd have in realtime, too.

**Comment by lye** [comment]
I think we've still got a few bytes to spare in there; I'll split that out to a separate PR tomorrow.

**Comment by lye** [comment]
After awhile looking at this, all of these roughly fall under #127 so I'm going to close this one out.

**Pull request closed without merging**
