### PR TITLE
Add specializations to /v2/characters

### PR DESCRIPTION
**Pull request by Eearslya**
Noticed there wasn't already a PR for this, so I went and made my own.

Nice and simple, exposing each character's currently equipped specs.

### CODE REVIEW

**Comment by darthmaim** [comment]
:+1:

**Comment by lye** [comment]
:+1:

I'm probably going to stuff it behind a `builds` scope or something  along those lines -- that new scope would give access to skills/traits/equipment. My idea putting it behind a new scope was mostly so you could expose your equipment without giving full inventory access (though `inventories` would also grant equipment access).

**Comment by Eearslya** [comment]
>I'm probably going to stuff it behind a `builds` scope or something along those lines

Updated the PR to reflect that.

**Comment by lye** [comment]
While implementing this, I made some changes to the output format. Sending a PR to a PR is kinda weird, so I just created a new one: #85 

>_>

**Pull request closed without merging**
