### PR TITLE
New format for /v2/floors, moved under /v2/continents

### PR DESCRIPTION
**Pull request by tivac**
The current format used by /v2/floors is difficult for a couple of reasons.

* Sectors, Tasks, Skill Challenges, and POIs are arrays. Finding a specific element is at best O(n).
* You can't request only a specific map/region/poi/etc, and the responses for an entire floor across a continent can be very large (200KB+)
* Every sub-field of a map has it's own id key (`task_id` vs `poi_id` vs `sector_id`)

This PR contains my proposed changes to the format to fix those problems.

* `/v2/floors` has been removed. You access floor information under `/v2/continents` because a floor requires a continent ID anyways.
* the `points_of_interest`, `tasks`, and `sectors` for a map are now objects with elements keyed by their id. Looking up any of these items can now be done in O(1) time.
* `poi_id`/`sector_id`/`task_id` have now been standardized to `id`.
* If a POI is on the `default_floor` for the map it doesn't repeat that information now.

There's another part of this proposal that should help with the issue of response size. You can now drill down even further into these objects to get a more concise view of the data you care about. All of these new endpoints support the standard pagination params and headers to ease iterating through them and selecting just the data you care about.

```js
// GET /v2/continents/1/floors
// GET /v2/continents/1/floors?ids=all
// GET /v2/continents/1/floors?ids=1,2
// GET /v2/continents/1/floors?page=0
// GET /v2/continents/1/floors/1/regions
// GET /v2/continents/1/floors/1/regions?ids=all
// GET /v2/continents/1/floors/1/regions?ids=1,2
// GET /v2/continents/1/floors/1/regions?page=0
// GET /v2/continents/1/floors/1/regions/1/maps
// GET /v2/continents/1/floors/1/regions/1/maps?ids=all
// GET /v2/continents/1/floors/1/regions/1/maps?ids=1,2
// GET /v2/continents/1/floors/1/regions/1/maps?page=0
// GET /v2/continents/1/floors/1/regions/1/maps/26/pois
// GET /v2/continents/1/floors/1/regions/1/maps/26/pois?ids=all
// GET /v2/continents/1/floors/1/regions/1/maps/26/pois?ids=1,2
// GET /v2/continents/1/floors/1/regions/1/maps/26/pois?page=0
// GET /v2/continents/1/floors/1/regions/1/maps/26/tasks
// GET /v2/continents/1/floors/1/regions/1/maps/26/tasks?ids=all
// GET /v2/continents/1/floors/1/regions/1/maps/26/tasks?ids=1,2
// GET /v2/continents/1/floors/1/regions/1/maps/26/tasks?page=0
// GET /v2/continents/1/floors/1/regions/1/maps/26/sectors
// GET /v2/continents/1/floors/1/regions/1/maps/26/sectors?ids=all
// GET /v2/continents/1/floors/1/regions/1/maps/26/sectors?ids=1,2
// GET /v2/continents/1/floors/1/regions/1/maps/26/sectors?page=0
```
The URLs do get a little hilariously long by the end, but I think it's worth it to be able to deeply select just the necessary data for a single POI/Task/Sector.

### CODE REVIEW

**Comment by msmolev** [comment]
Couple notes for URLs:
- "ids=all" seems to be redundant. If ids parameter is not specified, it means "all", right?
- as IDs of individual items (tasks, pois) are unique (within only continent, or globally?) separate endpoint can be provided just for retrieval by endpoint:
```
// GET /v2/continents/1/tasks?ids=1,2,3
// GET /v2/continents/1/landmarks?ids=32,33,34
```

**Comment by tivac** [comment]
@msmolev They're different. Compare [/v2/colors](https://api.guildwars2.com/v2/colors) vs. [/v2/colors?ids=all](https://api.guildwars2.com/v2/colors?ids=all) vs. [/v2/colors?ids=1,2,3](https://api.guildwars2.com/v2/colors?ids=1,2,3).

For API consistency almost every endpoint exposes data in this format. Changing that functionality in just this one place doesn't make sense.

**Comment by aRestless** [comment]
If I see that correctly, floors are only data containers, right? There's no data about their position on the map, right?

Would that even be feasible?

**Comment by tivac** [comment]
@aRestless A floor is continent-wide, essentially. Map coords wouldn't make any since. This isn't how I would have chosen to structure the data had I been starting fresh, but w/o large changes on the backend this is how the data is structured.

**Comment by dr-ishmael** [comment]
@tivac Do floors have any inherent relationship to the z-axis?  I know that within some maps, especially the multi-level cities like Rata Sum, this certainly seems to be the case, but I have no clue if that's just a coincidence of how the data structure is utilized.

**Comment by aRestless** [comment]
@ticac As also pointed out by @dr-ishmael there is the Z-Axis (or Y-Axis in world coordinates). And a thing why I thought floors might be restricted to certain areas is Stonemist Castle. If you enter the main chamber there and have your minimap on highest zoom level, the minimap actually zooms in even further. I thought that would have been related to floors.

**Comment by tivac** [comment]
@dr-ishmael @aRestless I don't know the answer to those questions. @lye might?

**Comment by lye** [comment]
I'm not gonna lie, I have no idea how the continent/floor/region/map stuff works. I'm almost certain, however, that we do not expose enough data to determine the current floor from the player's coordinates.

**Comment by aRestless** [comment]
Since there are some maps that have gaps in their floor ids (Ascalonian Catacombs for example), I came up with the idea that floor ids and the Y-Axis might be staticly bound together and that everything "between"  j*scaleFactor and (j+1)*scaleFactor would be on floor j or so and missing floor ids would indicate vertically larger floors.

However that can't be right, because the Silverwastes, a very vertical map, only has floor ids 0, 1 and 2.

Well, that's sad, but given that my use case (actually tracking user movement and projecting things into the game view and on the map) is a pretty specialised one, I'm not mad if that detail isn't supported. Thanks for checking in though.

**Comment by tivac** [comment]
Haven't seen any concerns that would prevent this from going in as-is, so I'm going to merge this PR. Will shoot to turn on the updates to `/v2/continents` (to add floor APIs) sometime next week.

**Pull request merged**
