### PR TITLE
Add fractallevel and comander to account

### PR DESCRIPTION
**Pull request by Plitzz**
Is it possible to bring commanderstatus and fractallevel to account?

### CODE REVIEW

**Comment by lye** [comment]
Seems reasonable. Will have to figure out where those are stored though.

**Comment by Plitzz** [comment]
Hallo,

ist es abschätzbar bis wann wir dieses Feature nutzen können?

Mit freundlichen Grüßen

Plitzz

**Comment by Plitzz** [comment]
Hello there,

I wanted to again inquire about the state of affairs.
Is it really that hard to figure out where the fractallevel and commander status are stored in order to integrate it into the account endpoint?

Your delivers many new endpoints but unfortunately older requests are not implemented.

greeting

Plitzz

**Comment by lye** [comment]
Time is short and the backlog is long. Sorry :(

**Comment by Plitzz** [comment]
Hello there,

great, fractal_level is live.
However, it now requires even rights for progression, see https://github.com/arenanet/api-cdi/issues/117.

Is there a reason for this procedure?

Best regards

Plitzz

**Pull request merged**
