### PR TITLE
Add WvW guild kdr endpoints.

### PR DESCRIPTION
**Pull request by lye**
Not really happy with the URL structure, open to suggestions.

Also still debating whether to make the guild query require authentication. Right now I'm leaning torwards "no".

### CODE REVIEW

**Comment by rikkuness** [comment]
Do you need all 3 of `["red", "green", "blue"]` ? Theoretically one of these values will always be 0 right?

**Comment by lye** [comment]
Many of the guilds actually have values for all three teams -- meaning they've got members repping (and killing) on two or more sides.

**Comment by rikkuness** [comment]
I'd never actually considered that possibility, cool :)

**Comment by lye** [comment]
This is technically live but looks like it's horribly broken. Will open a second issue for it.

**Comment by rikkuness** [comment]
I take it the `top` endpoint and stuff is "live" but the guild specific one still is not?

**Comment by lye** [comment]
Whoops, forgot to turn that on. Should be enabled in ~5 minutes.

**Pull request merged**
